apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: replicas.yaml
    target:
      kind: Deployment
      name: myKustom-app  # Replace with the actual resource name
configMapGenerator:
  - name: mykustom-map
    env: config.properties
